CREATE TABLE [dbo].[ShortUrl](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OriginalUrl] [nvarchar](4000) NOT NULL,
 CONSTRAINT [PK_ShortUrl] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO